Repository yiisoft/yii-dev-tool, pull requests merged in 2020-12, with the labels that each got.

#127 Add settings command
  composer.json
  config/.gitignore
  config/settings.php
  src/Command/Github/SettingsCommand.php
  src/Component/Console/YiiDevToolApplication.php
  src/Component/Package/Package.php
Labels: status:code review, type:feature

#128 Extract PackageError classes
  src/Command/Git/CommitCommand.php
  src/Command/Git/PullCommand.php
  src/Command/Git/PushCommand.php
  src/Command/Git/RequestPullCommand.php
  src/Command/InstallCommand.php
  src/Command/Replicate/ReplicateFilesCommand.php
  src/Command/TestCommand.php
  src/Component/Console/PackageCommand.php
  src/Component/Package/Package.php
  src/Component/Package/PackageError.php
  src/Component/Package/PackageErrorList.php
  src/Component/Package/PackageList.php
Labels: status:code review

#133 Improve composer/fix-dependencies command
  src/App/Command/Composer/ComposerFixDependenciesCommand.php
  src/Infrastructure/Composer/ComposerPackage.php
  src/Infrastructure/Composer/ComposerPackageUsageAnalyzer.php
  src/Infrastructure/Composer/Config/ComposerConfig.php
Labels: type:bug

#138 Replace "php.exe" with "php" for windows
  yii-dev.bat
Labels: status:code review

#141 Relative symlinks for containerized environment
  src/App/Command/InstallCommand.php
Labels: status:code review

#145 Refactor IO operations
  src/App/Command/Release/MakeCommand.php
  src/App/Component/Console/OutputManager.php
Labels: status:code review

#139 Rename command git/checkout-branch -> git/checkout
  src/App/Command/Git/CheckoutCommand.php
  src/App/YiiDevToolApplication.php
Labels: status:code review
